Mg/homologouscollapse
lanl/phoebus pull request #176
Opened 2023-06-15 17:29 UTC by mari2895

## PR Summary

## PR Checklist

- [ ] Adds a test for any bugs fixed. Adds tests for new features.
- [ ] Format your changes by calling `scripts/bash/format.sh`.
- [ ] Explain what you did.

2023-06-15 18:06 UTC, Yurlungur requested changes
Overall looks good! A few comments below. Can you also format the code by running that format script and committing the changed files?

2023-06-15 18:42 UTC, mari2895 commented on src/phoebus_utils/variables.hpp
> +constexpr char compweight[] = "compweight";
I can delete these, don't think we need it anymore. What do you think?

2023-06-15 18:45 UTC, mari2895 commented on src/radiation/radiation.cpp
> +    const Real lum = pin->GetOrAddReal("radiation", "lum", 4.0);
I think this is an old file, mine has 4.0.

2023-06-15 19:42 UTC, Yurlungur commented on src/phoebus_utils/variables.hpp
> +constexpr char compweight[] = "compweight";
I think maybe we still need tau. But I think the others can go away.

2023-06-15 19:57 UTC, Yurlungur commented on src/radiation/radiation.cpp
> +    const Real lum = pin->GetOrAddReal("radiation", "lum", 4.0);
The diff is showing it changed to 4.0. Nevertheless, just curious. What are the units here?

2023-06-28 15:33 UTC, Yurlungur approved these changes

2023-06-29 16:19 UTC, merged